// Import Web Components to register them
import '@eva-suite/sovereign-ui';

// Export React wrappers
export { EVAGCButton } from './components/EVAGCButton';
export { EVAGCHeader } from './components/EVAGCHeader';
export { EVAGCFooter } from './components/EVAGCFooter';
export { EVALanguageSwitcher } from './components/EVALanguageSwitcher';
export { EVAChatPanel } from './components/EVAChatPanel';
export { EVACard } from './components/EVACard';
export { EVADialog } from './components/EVADialog';
export { EVATabs } from './components/EVATabs';
export { EVASelect } from './components/EVASelect';
export { EVAPopover } from './components/EVAPopover';
export { EVACheckbox } from './components/EVACheckbox';
export { EVAInput } from './components/EVAInput';
export { EVASwitch } from './components/EVASwitch';
export { EVADrawer } from './components/EVADrawer';
export { EVATooltip } from './components/EVATooltip';
export { EVATextarea } from './components/EVATextarea';
export { EVALabel } from './components/EVALabel';
export { EVASeparator } from './components/EVASeparator';
export { EVAAccordion } from './components/EVAAccordion';
export { EVAAccordionItem } from './components/EVAAccordionItem';
export { EVAAvatar } from './components/EVAAvatar';
export { EVAAvatarImage } from './components/EVAAvatarImage';
export { EVAAvatarFallback } from './components/EVAAvatarFallback';
export { EVACollapsible } from './components/EVACollapsible';
export { EVACollapsibleTrigger } from './components/EVACollapsibleTrigger';
export { EVACollapsibleContent } from './components/EVACollapsibleContent';
export { EVADropdownMenu } from './components/EVADropdownMenu';
export { EVADropdownMenuItem } from './components/EVADropdownMenuItem';
export { EVADropdownMenuSeparator } from './components/EVADropdownMenuSeparator';
export { EVADropdownMenuLabel } from './components/EVADropdownMenuLabel';
export { EVAContextMenu } from './components/EVAContextMenu';
export { EVAContextMenuItem } from './components/EVAContextMenuItem';
export { EVABreadcrumb } from './components/EVABreadcrumb';
export { EVABreadcrumbList } from './components/EVABreadcrumbList';
export { EVABreadcrumbItem } from './components/EVABreadcrumbItem';
export { EVABreadcrumbLink } from './components/EVABreadcrumbLink';
export { EVABreadcrumbPage } from './components/EVABreadcrumbPage';
export { EVABreadcrumbSeparator } from './components/EVABreadcrumbSeparator';

// Export types
export type { EVAGCButtonProps } from './components/EVAGCButton';
export type { EVAGCHeaderProps } from './components/EVAGCHeader';
export type { EVAGCFooterProps } from './components/EVAGCFooter';
export type { EVALanguageSwitcherProps } from './components/EVALanguageSwitcher';
export type { EVAChatPanelProps, EVAChatPanelRef } from './components/EVAChatPanel';
export type { EVACardProps, EVACardRef } from './components/EVACard';
export type { EVADialogProps } from './components/EVADialog';
export type { EVATabsProps } from './components/EVATabs';
export type { EVASelectProps } from './components/EVASelect';
export type { EVAPopoverProps } from './components/EVAPopover';
export type { EVACheckboxProps as EVACheckboxPropsType } from './components/EVACheckbox';
export type { EVAInputProps } from './components/EVAInput';
export type { EVASwitchProps } from './components/EVASwitch';
export type { EVADrawerProps } from './components/EVADrawer';
export type { EVATooltipProps } from './components/EVATooltip';
export type { EVATextareaProps } from './components/EVATextarea';
export type { EVALabelProps } from './components/EVALabel';
export type { EVASeparatorProps } from './components/EVASeparator';
export type { EVAAccordionProps } from './components/EVAAccordion';
export type { EVAAccordionItemProps } from './components/EVAAccordionItem';
export type { EVAAvatarProps } from './components/EVAAvatar';
export type { EVAAvatarImageProps } from './components/EVAAvatarImage';
export type { EVAAvatarFallbackProps } from './components/EVAAvatarFallback';
export type { EVACollapsibleProps } from './components/EVACollapsible';
export type { EVACollapsibleTriggerProps } from './components/EVACollapsibleTrigger';
export type { EVACollapsibleContentProps } from './components/EVACollapsibleContent';
export type { EVADropdownMenuProps } from './components/EVADropdownMenu';
export type { EVADropdownMenuItemProps } from './components/EVADropdownMenuItem';
export type { EVADropdownMenuSeparatorProps } from './components/EVADropdownMenuSeparator';
export type { EVADropdownMenuLabelProps } from './components/EVADropdownMenuLabel';
export type { EVAContextMenuProps } from './components/EVAContextMenu';
export type { EVAContextMenuItemProps } from './components/EVAContextMenuItem';
export type { EVABreadcrumbProps } from './components/EVABreadcrumb';
export type { EVABreadcrumbListProps } from './components/EVABreadcrumbList';
export type { EVABreadcrumbItemProps } from './components/EVABreadcrumbItem';
export type { EVABreadcrumbLinkProps } from './components/EVABreadcrumbLink';
export type { EVABreadcrumbPageProps } from './components/EVABreadcrumbPage';
export type { EVABreadcrumbSeparatorProps } from './components/EVABreadcrumbSeparator';

export type * from './types';
