// Import Web Components to register them
import '@eva-suite/sovereign-ui';

// Export React wrappers
export { EVAGCButton } from './components/EVAGCButton';
export { EVAGCHeader } from './components/EVAGCHeader';
export { EVAGCFooter } from './components/EVAGCFooter';
export { EVALanguageSwitcher } from './components/EVALanguageSwitcher';
export { EVAChatPanel } from './components/EVAChatPanel';
export { EVACard } from './components/EVACard';
export { EVADialog } from './components/EVADialog';
export { EVATabs } from './components/EVATabs';
export { EVASelect } from './components/EVASelect';
export { EVAPopover } from './components/EVAPopover';
export { EVACheckbox } from './components/EVACheckbox';
export { EVAInput } from './components/EVAInput';
export { EVASwitch } from './components/EVASwitch';
export { EVADrawer } from './components/EVADrawer';
export { EVATooltip } from './components/EVATooltip';
export { EVATextarea } from './components/EVATextarea';
export { EVALabel } from './components/EVALabel';
export { EVASeparator } from './components/EVASeparator';
export { EVAAccordion } from './components/EVAAccordion';
export { EVAAccordionItem } from './components/EVAAccordionItem';
export { EVAAvatar } from './components/EVAAvatar';
export { EVAAvatarImage } from './components/EVAAvatarImage';
export { EVAAvatarFallback } from './components/EVAAvatarFallback';
export { EVACollapsible } from './components/EVACollapsible';
export { EVACollapsibleTrigger } from './components/EVACollapsibleTrigger';
export { EVACollapsibleContent } from './components/EVACollapsibleContent';
export { EVADropdownMenu } from './components/EVADropdownMenu';
export { EVADropdownMenuItem } from './components/EVADropdownMenuItem';
export { EVADropdownMenuSeparator } from './components/EVADropdownMenuSeparator';
export { EVADropdownMenuLabel } from './components/EVADropdownMenuLabel';
export { EVAContextMenu } from './components/EVAContextMenu';
export { EVAContextMenuItem } from './components/EVAContextMenuItem';
export { EVABreadcrumb } from './components/EVABreadcrumb';
export { EVABreadcrumbList } from './components/EVABreadcrumbList';
export { EVABreadcrumbItem } from './components/EVABreadcrumbItem';
export { EVABreadcrumbLink } from './components/EVABreadcrumbLink';
export { EVABreadcrumbPage } from './components/EVABreadcrumbPage';
export { EVABreadcrumbSeparator } from './components/EVABreadcrumbSeparator';
export { EVAMenubar } from './components/EVAMenubar';
export { EVAMenubarMenu } from './components/EVAMenubarMenu';
export { EVAMenubarItem } from './components/EVAMenubarItem';
export { EVATabsList } from './components/EVATabsList';
export { EVATabsTrigger } from './components/EVATabsTrigger';
export { EVATabsContent } from './components/EVATabsContent';
export { EVASelectItem } from './components/EVASelectItem';
export { EVARadioGroup } from './components/EVARadioGroup';
export { EVARadioGroupItem } from './components/EVARadioGroupItem';
export { EVAToggleGroup } from './components/EVAToggleGroup';
export { EVAToggleGroupItem } from './components/EVAToggleGroupItem';
export { EVATable } from './components/EVATable';
export { EVATableHeader } from './components/EVATableHeader';
export { EVATableBody } from './components/EVATableBody';
export { EVATableRow } from './components/EVATableRow';
export { EVATableHead } from './components/EVATableHead';
export { EVATableCell } from './components/EVATableCell';
export { EVACardHeader } from './components/EVACardHeader';
export { EVACardTitle } from './components/EVACardTitle';
export { EVACardDescription } from './components/EVACardDescription';
export { EVACardContent } from './components/EVACardContent';

// Export types
export type { EVAGCButtonProps } from './components/EVAGCButton';
export type { EVAGCHeaderProps } from './components/EVAGCHeader';
export type { EVAGCFooterProps } from './components/EVAGCFooter';
export type { EVALanguageSwitcherProps } from './components/EVALanguageSwitcher';
export type { EVAChatPanelProps, EVAChatPanelRef } from './components/EVAChatPanel';
export type { EVACardProps, EVACardRef } from './components/EVACard';
export type { EVADialogProps } from './components/EVADialog';
export type { EVATabsProps } from './components/EVATabs';
export type { EVASelectProps } from './components/EVASelect';
export type { EVAPopoverProps } from './components/EVAPopover';
export type { EVACheckboxProps as EVACheckboxPropsType } from './components/EVACheckbox';
export type { EVAInputProps } from './components/EVAInput';
export type { EVASwitchProps } from './components/EVASwitch';
export type { EVADrawerProps } from './components/EVADrawer';
export type { EVATooltipProps } from './components/EVATooltip';
export type { EVATextareaProps } from './components/EVATextarea';
export type { EVALabelProps } from './components/EVALabel';
export type { EVASeparatorProps } from './components/EVASeparator';
export type { EVAAccordionProps } from './components/EVAAccordion';
export type { EVAAccordionItemProps } from './components/EVAAccordionItem';
export type { EVAAvatarProps } from './components/EVAAvatar';
export type { EVAAvatarImageProps } from './components/EVAAvatarImage';
export type { EVAAvatarFallbackProps } from './components/EVAAvatarFallback';
export type { EVACollapsibleProps } from './components/EVACollapsible';
export type { EVACollapsibleTriggerProps } from './components/EVACollapsibleTrigger';
export type { EVACollapsibleContentProps } from './components/EVACollapsibleContent';
export type { EVADropdownMenuProps } from './components/EVADropdownMenu';
export type { EVADropdownMenuItemProps } from './components/EVADropdownMenuItem';
export type { EVADropdownMenuSeparatorProps } from './components/EVADropdownMenuSeparator';
export type { EVADropdownMenuLabelProps } from './components/EVADropdownMenuLabel';
export type { EVAContextMenuProps } from './components/EVAContextMenu';
export type { EVAContextMenuItemProps } from './components/EVAContextMenuItem';
export type { EVABreadcrumbProps } from './components/EVABreadcrumb';
export type { EVABreadcrumbListProps } from './components/EVABreadcrumbList';
export type { EVABreadcrumbItemProps } from './components/EVABreadcrumbItem';
export type { EVABreadcrumbLinkProps } from './components/EVABreadcrumbLink';
export type { EVABreadcrumbPageProps } from './components/EVABreadcrumbPage';
export type { EVABreadcrumbSeparatorProps } from './components/EVABreadcrumbSeparator';
export type { EVAMenubarProps } from './components/EVAMenubar';
export type { EVAMenubarMenuProps } from './components/EVAMenubarMenu';
export type { EVAMenubarItemProps } from './components/EVAMenubarItem';
export type { EVATabsListProps } from './components/EVATabsList';
export type { EVATabsTriggerProps } from './components/EVATabsTrigger';
export type { EVATabsContentProps } from './components/EVATabsContent';
export type { EVASelectItemProps } from './components/EVASelectItem';
export type { EVARadioGroupProps } from './components/EVARadioGroup';
export type { EVARadioGroupItemProps } from './components/EVARadioGroupItem';
export type { EVAToggleGroupProps } from './components/EVAToggleGroup';
export type { EVAToggleGroupItemProps } from './components/EVAToggleGroupItem';
export type { EVATableProps } from './components/EVATable';
export type { EVATableHeaderProps } from './components/EVATableHeader';
export type { EVATableBodyProps } from './components/EVATableBody';
export type { EVATableRowProps } from './components/EVATableRow';
export type { EVATableHeadProps } from './components/EVATableHead';
export type { EVATableCellProps } from './components/EVATableCell';
export type { EVACardHeaderProps } from './components/EVACardHeader';
export type { EVACardTitleProps } from './components/EVACardTitle';
export type { EVACardDescriptionProps } from './components/EVACardDescription';
export type { EVACardContentProps } from './components/EVACardContent';

export type * from './types';
